### ISSUE TITLE
Инструкция

### ISSUE THREAD

**Issue by SergeyParamonov** [drafterleo/pie-poem#1]
Не хватает краткой инструкции, как запустить проект и использовать уже натренерованную модель.

**Comment by drafterleo** [comment]
Чтобы поработать с моделью (poems_model,dat), я обычно загружаю в питоновскую консоль содержимое console_scripts.py.

сначала импорты (нужно, чтобы были установлены json, pymorphy2, gensim):

import semantics as sem
import data_model as dm
from pprint import pprint
from analyze_poem import *

Потом вгружаю word2vec модель (занимает некоторое время):
модели скачивал отсюда: http://ling.go.mail.ru/dsm/ru/about#models

w2v = sem.load_w2v_model("путь до word2vec модели")

Затем:
pm = dm.read_data_model("poems_model.dat") # загрузить пирожковую модель
pprint(similar_poems("запрос", pm, w2v, topn=5))  # 5 наиболее близких к "запросу" пирожка

P.S. Прошу прощения за сложность - это экспериментальный проект, поиграться с модельками - до сносного интерфейса пока руки не дошли.

**Comment by SergeyParamonov** [comment]
Вот это можно и вынести в ReadMe

**Comment by drafterleo** [comment]
Понял, сделаю :)
